server:
  port: 8080

spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/

welcome:
  message: Welcome Sambuja Cor.


file:
  uploadPath: D://FileUpload//excel//

logging:
  config: classpath:logback.xml